# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the TypeScript code using Smithery CLI
RUN npx @smithery/cli build src/index.ts --out build/index.cjs --transport shttp

# Set environment variable for Discord token
ENV DISCORD_TOKEN=""

# Expose port (will be set by Smithery via PORT env var)
EXPOSE 8080

# Default command to run the MCP server
# Smithery will handle the transport and port configuration automatically
CMD ["node", "build/index.cjs"]