# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the TypeScript code using Smithery CLI
RUN npx @smithery/cli build src/index.ts --out build/index.js --transport shttp

# Set environment variable for Discord token
ENV DISCORD_TOKEN=""

# Expose HTTP port
EXPOSE 8080

# Default command to run the MCP server with shttp transport and Discord token
CMD ["node", "build/index.js", "--transport", "shttp", "--port", "8080"]